# Generated by Django 4.2.1 on 2023-05-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Genre of books')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of books')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Books discription')),
                ('Genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.genre', verbose_name='Genre')),
            ],
        ),
    ]
