# Generated by Django 4.2.1 on 2023-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Genre of books')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Genre discription')),
            ],
        ),
    ]
