# Generated by Django 4.2.1 on 2023-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Publish house')),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name of books'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Genre of books'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Series of books'),
        ),
    ]
