# Generated by Django 4.2.1 on 2023-06-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_books_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='picture',
            field=models.ImageField(default='_', upload_to='uploads/%Y/%m/%d/', verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
