# Generated by Django 4.2.1 on 2023-07-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_books_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=5, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
